name: Docker

on:
  push:
    branches:
      - main
      - feat/docker

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t katydid-web-client .
