

name: publish

on:
  push:
    branches:
      - main
      - feat/docker

jobs:
  publish-katydid-web-client-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build katydid-web-client image
        run: |
          docker build . --tag ghcr.io/code-sherpas/katydid-web-client
          docker push ghcr.io/code-sherpas/katydid-web-client
