name: publish

on:
  push:
    branches:
      - main
      - feat/docker

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build katydid-web-client image
        run: |
          echo $PAT_TOKEN | docker login ghcr.io -u ashikka --password-stdin
        env:
          CR_PAT: ${{ secrets.PAT_TOKEN }}
